### ISSUE TITLE
why isn't the segmenter data a constant?

### ISSUE THREAD

**Issue by stevengj** [chezou/TinySegmenter.jl#1]
At runtime, every time you want to tokenize, you create a new `Segmenter()` object, which creates new copies of the dictionaries.   But these dictionaries never change, so they could just be constants.

Why even have a `Segmenter` data structure if these things have only one possible value?  Why not just define `const BC1 = ....` etcetera at the top level of the module, and just export a function `tokenize(text)`?

Later on, if you implement multiple segmentation algorithms, you can have `tokenize(text)` call your default algorithm, and `tokenize(segmenter, text)` call a different algorithm.  But this would require a redesign of the `Segmenter` type anyway in order to make it abstract, and even then you would just need a constant `tinysegmenter` singleton type so that `tokenize(tinysegmenter, text)` called the version using the global constants `BC1` etcetera.

Furthermore, if you put `VERSION >= v"0.4.0-dev+6521" && __precompile__()` at the top of `TinySegmenter.jl` (before the `module` statement), then all of the global constant dictionaries will get precompiled in Julia 0.4 or later.

**Comment by chezou** [comment]
To tell the truth, I tried to use `const` but I can't find out how to use it in Module. So I will rewrite to use `const`.
Thanks :smile:

**Comment by stevengj** [comment]
Just do `const BC1 = ....` etc. at the top level inside the module:

```
module TinySegmenter

....

const BC1 = ....

...

end
```

**Comment by chezou** [comment]
Thanks! d70914d

**Comment by stevengj** [comment]
Don't forget to update the README as well.

**Comment by chezou** [comment]
Thx! I fix it!  56bb7afdae58360abb1c78bbfe7dfdd0b434c840
