### ISSUE TITLE
chartype should be a Char?

### ISSUE THREAD

**Issue by stevengj** [chezou/TinySegmenter.jl#3]
Right now, you have `chartype::Array{Tuple{Regex,ASCIIString},1}`.  But since the char type is only ever a single character, why not just use `chartype::Array{Tuple{Regex,Char},1}`, with types of `'M'`, `'H'`, etcetera?  Single characters are much more efficient than strings.

**Comment by chezou** [comment]
`ismatch`'s second argument is assumed for `String`, so I think converting to String from Char will be required. https://github.com/chezou/TinySegmenter.jl/blob/master/src/TinySegmenter.jl#L62

Is there any efficient way, or is it still efficient using characters?

**Comment by stevengj** [comment]
It would be much more efficient to make `CHARTYPE` a `Dict{Char, Char}` rather than using regexes.

**Comment by chezou** [comment]
That is not reasonable.
These regexes include over 10,000+ characters(Hiragana, Katakana and Kanji), so using character dict makes down readability.

**Comment by stevengj** [comment]
Oh, I didn't see the `-` ranges.  Okay, then just use some ranges of chars.  Will still probably be more efficient than regexes.

**Comment by stevengj** [comment]
For example, this uses a `Dict` with 358 elements supplemented by 1 range, and is about 20 times faster than your `_ctype` function based on regexes in a simple benchmark (covering all the types):

``` jl
const CHARDICT = Dict{Char,Char}()
for c in "一二三四五六七八九十百千万億兆"
    CHARDICT[c] = 'M'
end
for c in "々〆ヵヶ"
    CHARDICT[c] = 'H'
end
for c in 'ぁ':'ん'
    CHARDICT[c] = 'I'
end
for c in 'ァ':'ヴ'
    CHARDICT[c] = 'K'
end
for c in "ーｰ\uff9e"
    CHARDICT[c] = 'K'
end
for c in 'ｱ':'ﾝ'
    CHARDICT[c] = 'K'
end
for c in ['a':'z';'A':'Z';'ａ':'ｚ';'Ａ':'Ｚ']
    CHARDICT[c] = 'A'
end
for c in ['0':'9';'０':'９']
    CHARDICT[c] = 'N'
end
function _ctype(c::Char)
    return get(CHARDICT, c, '一' <= c <= '龠' ? 'H' : 'O')
end
```

If you add `'一':'龠'` range to `CHARDICT` (with a loop, obviously), the dictionary size is increased to 21240 elements but the speed is not increased, so I think it's better to use the small dictionary above.

**Comment by stevengj** [comment]
You could shrink the code size above by using something like:

``` jl
for (chars,cat) in (("一二三四五六七八九十百千万億兆",'M'), ("々〆ヵヶ", 'H'), ('ぁ':'ん','I'), ('ァ':'ヴ','K'), ("ーｰ\uff9e",'K'), ('ｱ':'ﾝ','K'), (['a':'z';'A':'Z';'ａ':'ｚ';'Ａ':'Ｚ'],'A'), (['0':'9';'０':'９'],'N'))
    for c in chars
        CHARDICT[c] = cat
    end
end
```

**Comment by chezou** [comment]
@stevengj Thx! I used Character, finally. 92bf1565d61440e910325e4549351683f4a1c356
