### ISSUE TITLE
tokenize should accept AbstractString

### ISSUE THREAD

**Issue by stevengj** [chezou/TinySegmenter.jl#4]
Right now, `tokenize` requires the `text` argument to be a `UTF8String`.  However, if you just change the type to `AbstractString`, it looks like your code will work as-is with any string encoding, e.g. `UTF16String`.

**Comment by chezou** [comment]
Indeed.
First I considered performance, but it is early optimization so I fixed on fa35628 .

**Comment by stevengj** [comment]
@chezou, there is no performance disadvantage to making this argument an `AbstractString`.   For each string type that you pass to `tokenize`, Julia will compile a specialized version of `tokenize` for that type.  So, when you pass a `UTF8String` argument, it will generate _exactly_ the same JIT code as before.

(This is a common misconception about Julia.  Declaring argument types has zero impact on performance.  Argument types are best viewed as a filter: for what types does this method apply?  They are useful to enforce correctness, for dispatch of different types to different methods, and as information to the caller.)

**Comment by chezou** [comment]
That sounds nice! So I don't need to write a kind of useless argument types any more.
Thank you for your advice :)
