### ISSUE TITLE
segment should be an array of Char, not strings

### ISSUE THREAD

**Issue by stevengj** [chezou/TinySegmenter.jl#5]
Your `segment` array is currently an array of strings, which is pretty wasteful because almost all the elements are characters.

It seems like you could make `segment` an array of `Char` as well.  The only reason it is an array of strings is for the terminators `"B1"`, `"E1"`, etcetera, but it seems like you could just as easily use characters for these sentinels.  You just need 5 `Char` values that cannot occur in text, and for that you could use invalid unicode codepoints.  e.g. any `>= 0x110000`.

So you could initialize the `segment` array to `segment = [Char(0x110001), Char(0x110002), Char(0x110003)]` and then append `[Char(0x110004), Char(0x110005)]` at the end.  Then adjust your score dictionaries accordingly.

Also, the score dictionaries currently require you to construct strings.   Probably it would be more efficient for the keys of the dictionaries to be tuples of `Char`, e.g. `('H', 'H')` rather than `"HH"`.  Tuples are very efficient in Julia.

**Comment by chezou** [comment]
Thank you for your advice :) I fixed d81897b1cfb4c64150b4a8e5430e783975130fc4

**Comment by chezou** [comment]
The idea using invalid code point is very interesting. I didn't get the idea!

**Comment by stevengj** [comment]
FYI, I ran some benchmarks on the Tanaka corpus, and it looks like this change improved the performance by almost a factor of 10.
