### ISSUE TITLE
Benchmarks 

### ISSUE THREAD

**Issue by stevengj** [chezou/TinySegmenter.jl#8]
It would be interesting to perform some simple benchmarks, on a long Japanese text, against TinySegmenter implementations in other languages. 

This will let us know if we did a good job optimizing the code. I'm sure the julia-users mailing list would be interested in the results---it's always nice to have comparisons for an algorithm like this that has been implemented in many languages.

**Comment by chezou** [comment]
I've understood what you want! OK, I'll benchmark with other lanuages code.

**Comment by chezou** [comment]
I added benchmark scripts 69c732bc89eaa19ba2053b550a27e69ffb26acc2

I ran benchmark.sh and get following,

```
# node.js
v4.1.2
121.043sec

# Python
Python 2.7.8
## benchmarker:         release 4.0.1 (for python)
## python version:      2.7.8
## python compiler:     GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.51)
## python platform:     Darwin-14.5.0-x86_64-i386-64bit
## python executable:   /usr/local/opt/python/bin/python2.7
## cpu model:           Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
## parameters:          loop=1, cycle=1, extra=0

##                        real    (total    = user    + sys)
tokenize               99.9538   92.8500   91.7800    1.0700

## Ranking                real
tokenize               99.9538  (  0.0)

## Matrix                 real    [01]    [02]
[01] tokenize          99.9538     0.0   100.0

# Python3
## benchmarker:         release 4.0.1 (for python)
## python version:      3.5.0
## python compiler:     GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)
## python platform:     Darwin-14.5.0-x86_64-i386-64bit
## python executable:   /Users/mic/.pyenv/versions/3.5.0/bin/python
## cpu model:           Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
## parameters:          loop=1, cycle=1, extra=0

##                        real    (total    = user    + sys)
tokenize               31.5590   29.6400   29.2100    0.4300

## Ranking                real
tokenize               31.5590  (100.0) ********************

## Matrix                 real    [01]
[01] tokenize          31.5590   100.0

# Julia
julia version 0.4.0
12.358373 seconds (5.00 M allocations: 252.487 MB, 0.49% gc time)

# Ruby (too slow so that I reduce repeat times from 100 to 5)
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
                 user     system      total        real
segment     45.540000   1.120000  46.660000 ( 49.597821)
```

| Node.js | Python2 | Python3 | Julia | Ruby |
| --- | --- | --- | --- | --- |
| 121.04 | 92.85 | 29.64 | 12.36 | (933+) |

**Comment by stevengj** [comment]
Nice!   I wonder why Python3 is so much faster than Python2?

**Comment by stevengj** [comment]
I posted a [link to this on the julia-users mailing list](https://groups.google.com/d/msg/julia-users/afA_ZfoOUdU/cSShmnDNBQAJ).

**Comment by stevengj** [comment]
PS. Did you compare the results to see if Julia is giving the same word breaks?

**Comment by ScottPJones** [comment]
This is great stuff.  Do you have any comparisons to some of the C++ or Objective-C versions?
@stevengj I would think the difference is most likely because of the different Unicode string handling between Python2 and Python3.

**Comment by chezou** [comment]
@stevengj Thank you for your great co-operation!

@ScottPJones I found Objective-C [implementation](https://github.com/tnantoka/TinySegmenter.m) but I've never compiling Ob-C code with Xcode yet :sweat_smile: 
I also found [TinySegmenterMaker](https://github.com/shogo82148/TinySegmenterMaker/), which is learning tool of TinySegmenter and is including several language (c++, go, C# and so on) templates. I hope to pull request of Julia version and benchmarking with it :smile:

**Comment by stevengj** [comment]
@ScottPJones, I figured that, but I was wondering what specifically caused it to be 3x faster in python3.  Faster string construction/concatenation?  Better string garbage collection?  Faster unicode hashing or comparison?  But not something I care enough to track down (you'd have to run a profiler on cpython).

**Comment by stevengj** [comment]
TinySegmenterMaker includes a C++ version too; that should be easier to try out than the Objective-C version.  The Go version would also be interesting to try.

**Comment by chezou** [comment]
As @repeatedly said, Python version's loop number is 10, so I will re-benchmark after backing home.
(He also mentioned Julia implementation is not using `TC1`, `TC2`, `TC3`, `TC4`, and I fixed it 51217e964fd33b05a2bccd74a30a9991177762e6 )

**Comment by chezou** [comment]
I re-benchmarked same condition.

2.5 GHz Intel Core i5
8 GB 1600 MHz DDR3

```
# Ruby 2.2.3 with patched version https://github.com/6/tiny_segmenter/pull/1
~/.j/v/T/benchmark git:master ❯❯❯ RUBYLIB=./lib/tiny_segmenter/lib ruby benchmark.rb                                    ✱ ◼
                 user     system      total        real
segment     19.010000   0.430000  19.440000 ( 20.324273)

# Julia 0.4.0
~/.j/v/T/benchmark git:master ❯❯❯ julia4 -L ../src/TinySegmenter.jl benchmark.jl                                        ✱ ◼
  1.458671 seconds (503.89 k allocations: 25.378 MB, 0.82% gc time)

# Python 3.5.0
~/.j/v/T/benchmark git:master ❯❯❯ python tinysegmenter3.py                                                              ✱ ◼
## benchmarker:         release 4.0.1 (for python)
## python version:      3.5.0
## python compiler:     GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)
## python platform:     Darwin-14.5.0-x86_64-i386-64bit
## python executable:   /Users/mic/.pyenv/versions/3.5.0/bin/python
## cpu model:           Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
## parameters:          loop=1, cycle=1, extra=0

##                        real    (total    = user    + sys)
tokenize               24.1842   23.9400   23.7600    0.1800

## Ranking                real
tokenize               24.1842  (100.0) ********************

## Matrix                 real    [01]
[01] tokenize          24.1842   100.0

# Python 2.7.8
~/.j/v/T/benchmark git:master ❯❯❯ python tinysegmenter.py                                                               ✱ ◼
## benchmarker:         release 4.0.1 (for python)
## python version:      2.7.8
## python compiler:     GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.51)
## python platform:     Darwin-14.5.0-x86_64-i386-64bit
## python executable:   /usr/local/opt/python/bin/python2.7
## cpu model:           Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
## parameters:          loop=1, cycle=1, extra=0

##                        real    (total    = user    + sys)
tokenize               96.2124   93.0800   92.2400    0.8400

## Ranking                real
tokenize               96.2124  (100.0) ********************

## Matrix                 real    [01]
[01] tokenize          96.2124   100.0

# Node.js
~/.j/v/T/benchmark git:master ❯❯❯ node benchmark.js                                                                     ⬆ ◼
9.622sec
```

So following are new result (each 10 times loop)

| JavaScript (Node.js) | Python2 | Python3 | Julia | Ruby |
| --- | --- | --- | --- | --- |
| 9.62 | 93.08 | 23.94 | 1.46 | 19.44 |

**Comment by stevengj** [comment]
It would be nice to put these benchmark results in the README.

(Probably label the "Node.js" column as "JavaScript (Node.js)".)

**Comment by ScottPJones** [comment]
Very nice, very compelling numbers, and the techniques that the two of you came up to optimize Julia performance for strings here with are very applicable to what we're doing.
(maybe the sort of thing to go into performance tips?)
Great job!

**Comment by ScottPJones** [comment]
@stevengj About the Python2 vs. Python3, from past experience, I'd bet it was due to Python2 using UTF16 (even if the strings only have UCS2 characters), while Python3 recognizes that a string only has UCS2 and always does direct indexing, unlike Python2 and Julia.

**Comment by chezou** [comment]
Finally, I implemented Julia version of TinySegmenterMaker template
https://github.com/shogo82148/TinySegmenterMaker/pull/10

| Ruby | C++ | Perl | Node.js | Go | Python | Python(tinysegmenter3) | Julia |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 132.98 | 48 | 134 | 105.31 | 10.50 | 162.44 | 111.85 | 11.70 |

After my blog post, @ikawaha optimized [golang version](https://github.com/ikawaha/tinysegmenter.go/commits/master) using same optimization we did (see more detail in [his blog post in Japanese](http://ikawaha.hateblo.jp/entry/2015/10/23/161351)).

There were some optimization for python and it gets faster nearly Node.js.

**Comment by stevengj** [comment]
Cool!  You might want to update the README.

Performance within 10% of the Go version is pretty darn good, I think we can be happy with it (Go is a statically typed, compiled language, the sort that you traditionally expect to be able to get top performance from).

However, I should point out that the Go version implemented additional tricks that we could potentially copy.  In particular, for several of the dictionaries it packed values into 64-bit integers rather than using tuples, and that should certainly speed things up a bit for Julia too.

**Comment by stevengj** [comment]
(@ikawaha is correct that this is not purely a comparison between languages because we also optimized the algorithm.   However, the key point is that it is _possible_ to heavily optimize Julia code in a way that makes it competitive with similarly optimized code in a traditional statically compiled language like Go.   I don't think it would be possible to get this level of performance in pure CPython or Ruby, although they could certainly be sped up somewhat.)

**Comment by chezou** [comment]
Updated README :)

I heard @ikawaha that the optimization with packing was done by @shogo82148 - the author of TinySegmenterMaker.

**Comment by chezou** [comment]
@bicycle1885 created a patch to speed up hashing, and become 10% faster.

https://gist.github.com/bicycle1885/918a0fee5dbb3d68f05a

``` sh
❯❯❯ julia4 -L ../src/TinySegmenter.jl benchmark.jl                                                                      ✭ ✱ ◼
 10.353674 seconds (5.36 M allocations: 263.428 MB, 0.58% gc time)
```

**Comment by stevengj** [comment]
Cool!  That's the sort of optimization that might even be worthwhile to include in Base julia.

**Comment by bicycle1885** [comment]
I'll make a pull request to `Base` when I come up with a smart way to implement it :smiley: .

**Comment by stevengj** [comment]
One caveat is that the hash algorithm in base is designed such that the same number always hashes to the same value, regardless of the numeric type, IIRC. So this might conflict with that goal.
