### ISSUE TITLE
Validation against other implementations

### ISSUE THREAD

**Issue by stevengj** [chezou/TinySegmenter.jl#9]
Currently, the `tests/` directory has a small number of simple tests, but we've subsequently found several bugs that were not caught by these tests.

It would be good to validate TinySegmenter.jl by comparing its output on a long text to one of the other implementations (e.g. those in #8).

**Comment by chezou** [comment]
It sounds nice.
But it is difficult problem for NLP how long text is enough to test.

Anyway, I also think current test is too short to validate. I'll try to prepare more long text.

**Comment by stevengj** [comment]
Why not test it against the same text as the benchmark?   i.e. test with a huge text.

**Comment by chezou** [comment]
The benchmark text is under CC BY-SA 2.0, so I'll add it for test code :smile:

**Comment by chezou** [comment]
There are still some diff between JS output and Julia's one https://gist.github.com/chezou/e181f7c1e7c22986f16d
I'll investigate after tomorrow release on my job :sweat_drops:

**Comment by chezou** [comment]
I confirmed there are no difference between 0f03beab71dc780d9c022fbd07decb5ddb2a345e (patching 51217e964fd33b05a2bccd74a30a9991177762e6 ) and HEAD implementation.

**Comment by chezou** [comment]
I found suspicious point.
`ctype()` might be broken.

```jl
julia> length([Char(ctype(c)) for c in '一':'龠'])
20897

julia> count(c -> (c != 'H'), [Char(ctype(c)) for c in '一':'龠'])
15
```

**Comment by chezou** [comment]
Finally I found the bug and fixed it. https://github.com/chezou/TinySegmenter.jl/commit/f94cc76766fc42770c9bb45a4b04865d52fe21db

Next, I'll create test.
